from html import escape

from src.analysis_engine import analyse_category
from src.root_cause_engine import identify_root_cause
from src.recommendation_engine import recommend_actions
from src.llm_commentary_generator import generate_llm_commentary
from src.executive_summary_generator import generate_executive_summary


def to_html_block(text: str) -> str:
    return escape(str(text)).replace("\n", "<br>")


def get_top_priority(category_results: list) -> dict:
    return sorted(
        category_results,
        key=lambda result: result["analysis"]["revenue_change_pct"]
    )[0]


def generate_manager_brief(df, manager_email: str) -> str:
    manager_rows = df[df["manager_email"] == manager_email]

    if manager_rows.empty:
        return f"<p>No trading data found for manager: {escape(manager_email)}</p>"

    manager_name = manager_rows.iloc[0]["manager_name"]
    category_results = []

    assignments = manager_rows[["market", "category"]].drop_duplicates()

    for _, row in assignments.iterrows():
        market = row["market"]
        category = row["category"]

        analysis = analyse_category(df, market, category)
        root_cause = identify_root_cause(analysis)
        recommendations = recommend_actions(root_cause)

        commentary = generate_llm_commentary(
            analysis,
            root_cause,
            recommendations
        )

        category_results.append({
            "analysis": analysis,
            "root_cause": root_cause,
            "recommendations": recommendations,
            "commentary": commentary,
        })

    executive_summary = generate_executive_summary(category_results)
    top_priority = get_top_priority(category_results)

    priority_market = top_priority["analysis"]["market"]
    priority_category = top_priority["analysis"]["category"]
    revenue_change = top_priority["analysis"]["revenue_change_pct"]
    traffic_change = top_priority["analysis"]["traffic_change_pct"]
    conversion_change = top_priority["analysis"]["conversion_change_pct"]
    margin_change = top_priority["analysis"]["margin_change_pct"]
    primary_driver = top_priority["root_cause"]["primary_driver"].replace("_", " ").title()
    confidence = top_priority["root_cause"]["confidence"].title()

    html = f"""
    <div style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.5;">
        <h1 style="color:#111827; margin-bottom: 8px;">
            📊 Weekly Trading Intelligence Brief
        </h1>

        <p style="margin-top: 0; color:#4b5563;">
            <strong>Prepared For:</strong> {escape(str(manager_name))}<br>
            <strong>Email:</strong> {escape(manager_email)}<br>
            <strong>Reporting Period:</strong> Previous Trading Week<br>
            <strong>Generated By:</strong> AI Trading Assistant
        </p>

        <hr style="border: none; border-top: 1px solid #d1d5db; margin: 24px 0;">

        <h2 style="color:#2563eb;">Executive Snapshot</h2>

        <table style="border-collapse: collapse; width: 100%; margin-bottom: 24px;">
            <tr>
                <td style="border:1px solid #e5e7eb; padding:12px; background:#f9fafb;">
                    <strong>Top Priority</strong><br>
                    {escape(str(priority_market))} | {escape(str(priority_category))}
                </td>
                <td style="border:1px solid #e5e7eb; padding:12px; background:#f9fafb;">
                    <strong>Revenue Movement</strong><br>
                    {revenue_change}%
                </td>
                <td style="border:1px solid #e5e7eb; padding:12px; background:#f9fafb;">
                    <strong>Primary Driver</strong><br>
                    {escape(primary_driver)}
                </td>
                <td style="border:1px solid #e5e7eb; padding:12px; background:#f9fafb;">
                    <strong>Confidence</strong><br>
                    {escape(confidence)}
                </td>
            </tr>
        </table>

        <h2 style="color:#2563eb;">Key Trading Metrics</h2>

        <table style="border-collapse: collapse; width: 100%; margin-bottom: 24px;">
            <tr style="background:#f3f4f6;">
                <th style="border:1px solid #e5e7eb; padding:10px; text-align:left;">Metric</th>
                <th style="border:1px solid #e5e7eb; padding:10px; text-align:left;">Movement</th>
            </tr>
            <tr>
                <td style="border:1px solid #e5e7eb; padding:10px;">Revenue</td>
                <td style="border:1px solid #e5e7eb; padding:10px;">{revenue_change}%</td>
            </tr>
            <tr>
                <td style="border:1px solid #e5e7eb; padding:10px;">Traffic</td>
                <td style="border:1px solid #e5e7eb; padding:10px;">{traffic_change}%</td>
            </tr>
            <tr>
                <td style="border:1px solid #e5e7eb; padding:10px;">Conversion</td>
                <td style="border:1px solid #e5e7eb; padding:10px;">{conversion_change}%</td>
            </tr>
            <tr>
                <td style="border:1px solid #e5e7eb; padding:10px;">Margin</td>
                <td style="border:1px solid #e5e7eb; padding:10px;">{margin_change}%</td>
            </tr>
        </table>

        <h2 style="color:#2563eb;">Executive Summary</h2>
        <p>{to_html_block(executive_summary)}</p>

        <h2 style="color:#2563eb;">Recommended Leadership Actions</h2>
        <ul>
            <li>Review performance for the highest-priority category.</li>
            <li>Investigate the identified revenue driver and supporting metrics.</li>
            <li>Validate stock availability, pricing, promotions and traffic acquisition activity.</li>
            <li>Prioritise corrective actions for categories showing the steepest weekly decline.</li>
        </ul>

        <hr style="border: none; border-top: 1px solid #d1d5db; margin: 24px 0;">

        <h2 style="color:#2563eb;">Category Detail</h2>
    """

    for result in category_results:
        analysis = result["analysis"]
        commentary = result["commentary"]
        root_cause = result["root_cause"]
        recommendations = result["recommendations"]

        html += f"""
        <div style="margin-top: 24px; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px;">
            <h3 style="margin-top:0; color:#111827;">
                {escape(str(analysis["market"]))} | {escape(str(analysis["category"]))}
            </h3>

            <p>
                <strong>Revenue:</strong> {analysis["revenue_change_pct"]}%<br>
                <strong>Traffic:</strong> {analysis["traffic_change_pct"]}%<br>
                <strong>Conversion:</strong> {analysis["conversion_change_pct"]}%<br>
                <strong>Margin:</strong> {analysis["margin_change_pct"]}%<br>
                <strong>Root Cause:</strong> {escape(str(root_cause["primary_driver"]).replace("_", " ").title())}<br>
                <strong>Confidence:</strong> {escape(str(root_cause["confidence"]).title())}
            </p>

            <h4 style="color:#111827;">AI Commentary</h4>
            <p>{to_html_block(commentary)}</p>

            <h4 style="color:#111827;">Recommended Actions</h4>
            <ul>
        """

        for action in recommendations.get("actions", []):
            html += f"<li>{escape(str(action))}</li>"

        html += f"""
            </ul>

            <p>
                <strong>Source:</strong>
                <a href="{escape(str(analysis["source_link"]))}">
                    {escape(str(analysis["source_link"]))}
                </a>
            </p>
        </div>
        """

    html += """
        <hr style="border: none; border-top: 1px solid #d1d5db; margin: 24px 0;">
        <p style="font-size:12px; color:#6b7280;">
            Generated by AI Trading Assistant using Azure Functions, OpenAI and Power Automate.
        </p>
    </div>
    """

    return html